const CONSORCIOS = [
  {
    "numero": 22,
    "nombre": "Consorcio Caminero Nº 22  \"Colonia Popular - Laguna Blanca\"",
    "localidad": "Colonia Popular - Laguna Blanca",
    "zona": "ZI",
    "color": "#6baed6",
    "latitude": -27.275505,
    "longitude": -59.147412,
    "red_km": 156.82,
    "red_primaria": 0,
    "red_secundaria": 25.7,
    "red_terciaria": 131.12,
    "presidente": "GONZÁLEZ, Pedro Maximiliano",
    "vicepresidente": "BASTIANI, Pedro Eugenio",
    "secretario": "MIRCOVICH, María Adela",
    "tesorero": "CODUTTI, Claudia Beatriz"
  },
  {
    "numero": 5,
    "nombre": "Consorcio Caminero Nº 5  \"Santa Elena\"",
    "localidad": "Santa Elena",
    "zona": "ZI",
    "color": "#6baed6",
    "latitude": -26.998478,
    "longitude": -59.85201,
    "red_km": 356.54,
    "red_primaria": 0,
    "red_secundaria": 77.66,
    "red_terciaria": 278.88,
    "presidente": "PEREZ, Nicolas Eusebio",
    "vicepresidente": "BALLESTEROS, José Antonio",
    "secretario": "YVANOVICH, Juan Jorge",
    "tesorero": "DOLCE, Jorge Oscar"
  },
  {
    "numero": 102,
    "nombre": "Consorcio Caminero Nº 102  \"Makallé\"",
    "localidad": "Makallé",
    "zona": "ZI",
    "color": "#6baed6",
    "latitude": -27.210375,
    "longitude": -59.285474,
    "red_km": 210.26,
    "red_primaria": 28.31,
    "red_secundaria": 0,
    "red_terciaria": 181.95,
    "presidente": "DALSEGGIO, Federico Antonio",
    "vicepresidente": "HORTT, Walter Omar",
    "secretario": "DELLAMEA, Pedro Moises",
    "tesorero": "FORTIN, Silvio Rolando"
  },
  {
    "numero": 16,
    "nombre": "Consorcio Caminero Nº 16  \"La Verde\"",
    "localidad": "La Verde",
    "zona": "ZI",
    "color": "#6baed6",
    "latitude": -27.121963,
    "longitude": -59.379889,
    "red_km": 119.61,
    "red_primaria": 20.53,
    "red_secundaria": 0,
    "red_terciaria": 99.08,
    "presidente": "CANAL, Oscar Alfredo",
    "vicepresidente": "LUQUE, Juan Carlos",
    "secretario": "SUAREZ, Eduardo",
    "tesorero": "GRABRE, Hector Antonio"
  },
  {
    "numero": 26,
    "nombre": "Consorcio Caminero Nº 26  \"Margarita Belén\"",
    "localidad": "Margarita Belén",
    "zona": "ZI",
    "color": "#6baed6",
    "latitude": -27.264493,
    "longitude": -58.971102,
    "red_km": 160.04,
    "red_primaria": 11.11,
    "red_secundaria": 0,
    "red_terciaria": 148.93,
    "presidente": "STELLA, Roberto Raul",
    "vicepresidente": "LACLAU, Omar Alberto",
    "secretario": "CABALLERO, Sixto Ruben",
    "tesorero": "DEL RIO, Jose Antonio"
  },
  {
    "numero": 37,
    "nombre": "Consorcio Caminero Nº 37  \"Colonia Tacuarí Oeste\"",
    "localidad": "Colonia Tacuarí Oeste",
    "zona": "ZI",
    "color": "#6baed6",
    "latitude": -27.965622,
    "longitude": -59.224337,
    "red_km": 188.64,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 188.64,
    "presidente": "MENDEZ, Juan Alejandro",
    "vicepresidente": "FANTIN, Felix Armando",
    "secretario": "KUCINSKAS, Casimiro Oscar",
    "tesorero": "FERNANDEZ, Joaquin Ildefonso"
  },
  {
    "numero": 38,
    "nombre": "Consorcio Caminero Nº 38  \"Basail\"",
    "localidad": "Basail",
    "zona": "ZI",
    "color": "#6baed6",
    "latitude": -27.882893,
    "longitude": -59.278493,
    "red_km": 341.5,
    "red_primaria": 5.35,
    "red_secundaria": 0,
    "red_terciaria": 336.15,
    "presidente": "MASIN, Marcelo Daniel",
    "vicepresidente": "BEAUVAIS, Juan Carlos",
    "secretario": "MORALES VELASCO, Mauricio José",
    "tesorero": "FANTIN, Julio Cesar"
  },
  {
    "numero": 40,
    "nombre": "Consorcio Caminero Nº 40  \"Puerto Tirol\"",
    "localidad": "Puerto Tirol",
    "zona": "ZI",
    "color": "#6baed6",
    "latitude": -27.376597,
    "longitude": -59.092046,
    "red_km": 148.06,
    "red_primaria": 0,
    "red_secundaria": 31.81,
    "red_terciaria": 116.25,
    "presidente": "IBARRA Germán",
    "vicepresidente": "PASCUAL, Luisa Lucia",
    "secretario": "CAMPESTRINI, Ana María",
    "tesorero": "CAMPESTRINI, Marcelino Pedro"
  },
  {
    "numero": 44,
    "nombre": "Consorcio Caminero Nº 44  \"Cote Lai\"",
    "localidad": "Cote Lai",
    "zona": "ZI",
    "color": "#6baed6",
    "latitude": -27.529507,
    "longitude": -59.571881,
    "red_km": 156.6,
    "red_primaria": 19.93,
    "red_secundaria": 42.74,
    "red_terciaria": 93.93,
    "presidente": "LOPEZ SOTO, Jorge Miguel",
    "vicepresidente": "CABRAL, Jose Máximo",
    "secretario": "CODUTTI, Roberto Javier",
    "tesorero": "ECHAZARRETA, Alberto Rolando"
  },
  {
    "numero": 45,
    "nombre": "Consorcio Caminero Nº 45  \"Las Garcitas\"",
    "localidad": "Las Garcitas",
    "zona": "ZI",
    "color": "#6baed6",
    "latitude": -26.616344,
    "longitude": -59.798826,
    "red_km": 190.65,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 190.65,
    "presidente": "BENITEZ, Rene Armando",
    "vicepresidente": "PRIETO, Fernando",
    "secretario": "ALONSO, Jorge Ismael",
    "tesorero": "SABADINI, Emilio Raúl"
  },
  {
    "numero": 54,
    "nombre": "Consorcio Caminero Nº 54 \"Capitán Solari\"",
    "localidad": "Capitán Solari",
    "zona": "ZI",
    "color": "#6baed6",
    "latitude": -26.806404,
    "longitude": -59.553851,
    "red_km": 180.94,
    "red_primaria": 7.52,
    "red_secundaria": 0,
    "red_terciaria": 173.42,
    "presidente": "MENDOZA, Vilmo Roberto",
    "vicepresidente": "AGUIRRE, Mario Jorge",
    "secretario": "VELAZQUEZ, Lidia Argentina",
    "tesorero": "GALARZA, Lucio"
  },
  {
    "numero": 62,
    "nombre": "Consorcio Caminero Nº 62  \"Colonia Benítez\"",
    "localidad": "Colonia Benítez",
    "zona": "ZI",
    "color": "#6baed6",
    "latitude": -27.314552,
    "longitude": -58.966166,
    "red_km": 152.61,
    "red_primaria": 12.74,
    "red_secundaria": 27.83,
    "red_terciaria": 112.04,
    "presidente": "DELLAMEA, Roberto Emilio",
    "vicepresidente": "VALUSSI, Daniel Oreste",
    "secretario": "DELLAMEA, Patricia Alejandra",
    "tesorero": "COLCOMBET, Rolando Maria"
  },
  {
    "numero": 64,
    "nombre": "Consorcio Caminero Nº 64  \"Colonia Elisa\"",
    "localidad": "Colonia Elisa",
    "zona": "ZI",
    "color": "#6baed6",
    "latitude": -26.929324,
    "longitude": -59.523625,
    "red_km": 206.8,
    "red_primaria": 15.87,
    "red_secundaria": 23.14,
    "red_terciaria": 167.79,
    "presidente": "REY, Luciano Alberto",
    "vicepresidente": "LOPEZ, Juan Fidel",
    "secretario": "BARRIOS, Jorge Vicente",
    "tesorero": "NUÑEZ, Florencio"
  },
  {
    "numero": 65,
    "nombre": "Consorcio Caminero Nº 65  \"Colonia Tacuarí Este\"",
    "localidad": "Colonia Tacuarí Este",
    "zona": "ZI",
    "color": "#6baed6",
    "latitude": -27.530374,
    "longitude": -58.989271,
    "red_km": 213.08,
    "red_primaria": 0,
    "red_secundaria": 57.68,
    "red_terciaria": 155.4,
    "presidente": "FERREYRA, Dugaldo Edgar Daniel",
    "vicepresidente": "GALASSI, Luis Omar",
    "secretario": "GARCIA, Marta Esther",
    "tesorero": "ZUAZQUITA, Hector Osvaldo"
  },
  {
    "numero": 67,
    "nombre": "Consorcio Caminero Nº 67  \"Tapenagá\"",
    "localidad": "Tapenagá",
    "zona": "ZI",
    "color": "#6baed6",
    "latitude": -27.654018,
    "longitude": -59.860738,
    "red_km": 221.53,
    "red_primaria": 0,
    "red_secundaria": 36.28,
    "red_terciaria": 185.25,
    "presidente": "TOURN, Roberto Abel",
    "vicepresidente": "PICECH, Carlos Javier",
    "secretario": "CINAT, Enrique Fermin",
    "tesorero": "RHINER, Hernan Alfonso"
  },
  {
    "numero": 7,
    "nombre": "Consorcio Caminero Nº7 \"Quitilipi\"",
    "localidad": "Quitilipi",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.870909,
    "longitude": -60.222766,
    "red_km": 279.18,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 279.18,
    "presidente": "VUCKO, Hugo José",
    "vicepresidente": "VUCKO, Miguel",
    "secretario": "TERZICH, Amalio",
    "tesorero": "RODRIGUEZ, Antonio"
  },
  {
    "numero": 9,
    "nombre": "Consorcio Caminero Nº9 \"Campo largo\"",
    "localidad": "Campo largo",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.80399,
    "longitude": -60.842311,
    "red_km": 354.24,
    "red_primaria": 0,
    "red_secundaria": 57.92,
    "red_terciaria": 296.32,
    "presidente": "MELLINGER, Andres Gustavo",
    "vicepresidente": "HRYC, Gerardo Antonio",
    "secretario": "JEPPESEN, Juan Ricardo",
    "tesorero": "VEGA, Sergio Gustavo"
  },
  {
    "numero": 105,
    "nombre": "Consorcio Caminero Nº105 \"El palmar\"",
    "localidad": "El palmar",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.45646,
    "longitude": -60.165223,
    "red_km": 145.57,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 145.57,
    "presidente": "ZELUK, Pedro Alfredo",
    "vicepresidente": "LUQUES, Gregorio Rolando",
    "secretario": "SUAREZ, Yolando Ramon",
    "tesorero": "MISTAL, Oscar Hugo"
  },
  {
    "numero": 12,
    "nombre": "Consorcio Caminero Nº12 \"Corzuela\"",
    "localidad": "Corzuela",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.961418,
    "longitude": -60.961453,
    "red_km": 477.2,
    "red_primaria": 0,
    "red_secundaria": 35.75,
    "red_terciaria": 441.45,
    "presidente": "RADIS, Blas Miguel",
    "vicepresidente": "BARALE, Miguel Angel",
    "secretario": "HERRERA, José Nicanor",
    "tesorero": "OSTOICH, Rafael"
  },
  {
    "numero": 13,
    "nombre": "Consorcio Caminero Nº13 \"Pampa del infierno\"",
    "localidad": "Pampa del infierno",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.502161,
    "longitude": -61.167966,
    "red_km": 927.45,
    "red_primaria": 0,
    "red_secundaria": 41.99,
    "red_terciaria": 885.46,
    "presidente": "DI SCIASCIO, Omar José",
    "vicepresidente": "CORBALAN, Ramón Alberto",
    "secretario": "SLABICH, Mateo",
    "tesorero": "MARCHEK, Antonio Oscar"
  },
  {
    "numero": 15,
    "nombre": "Consorcio Caminero Nº15 \"La tambora\"",
    "localidad": "La tambora",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.615225,
    "longitude": -60.054526,
    "red_km": 202.64,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 202.64,
    "presidente": "MARIANOVICH, Carlos Ruben",
    "vicepresidente": "YVANOVICH, Ivan Tito",
    "secretario": "MARCON, David Alfredo",
    "tesorero": "RETAMOZO, Roberto Oscar"
  },
  {
    "numero": 24,
    "nombre": "Consorcio Caminero Nº24 \"Pampa grande\"",
    "localidad": "Pampa grande",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.52443,
    "longitude": -60.573105,
    "red_km": 234.59,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 234.59,
    "presidente": "SNITIL, Victor Ricardo",
    "vicepresidente": "ARGAÑARAZ, Carlos Manuel",
    "secretario": "SVOBODA, Juan Valerio",
    "tesorero": "JAKES, Carlos Dardo"
  },
  {
    "numero": 25,
    "nombre": "Consorcio Caminero Nº25 \"Machagai\"",
    "localidad": "Machagai",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.92923,
    "longitude": -60.055189,
    "red_km": 458.47,
    "red_primaria": 0,
    "red_secundaria": 27.28,
    "red_terciaria": 431.19,
    "presidente": "ZAMORA, Walter Hernan",
    "vicepresidente": "POPOVICH, Juan Carlos",
    "secretario": "BIGLIA, Sergio Rene",
    "tesorero": "KRAMER, Walter Manfredo"
  },
  {
    "numero": 29,
    "nombre": "Consorcio Caminero Nº29 \"Concepción del bermejo\"",
    "localidad": "Concepción del bermejo",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.604242,
    "longitude": -60.950317,
    "red_km": 283.52,
    "red_primaria": 0,
    "red_secundaria": 32.56,
    "red_terciaria": 250.96,
    "presidente": "CURIN, Pablo Alberto",
    "vicepresidente": "PLANJAR, Alfredo",
    "secretario": "MERCANTI, Marcelo Guillermo",
    "tesorero": "LOPEZ, Dionicio Oscar"
  },
  {
    "numero": 30,
    "nombre": "Consorcio Caminero Nº30 \"Napenay\"",
    "localidad": "Napenay",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.734358,
    "longitude": -60.616482,
    "red_km": 276.25,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 276.25,
    "presidente": "LOPEZ, Jorge Alberto",
    "vicepresidente": "ORTIZ, Domingo Bartolome",
    "secretario": "GOMEZ, Daniel Ernesto",
    "tesorero": "AGUDO, Fernando Luis"
  },
  {
    "numero": 36,
    "nombre": "Consorcio Caminero Nº36 \"El tacuruzal\"",
    "localidad": "El tacuruzal",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.356762,
    "longitude": -60.16306,
    "red_km": 209.04,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 209.04,
    "presidente": "DE DOMINGO, Mariano",
    "vicepresidente": "SANCHEZ, Elpidio Cesar",
    "secretario": "ESCALANTE, Benito Antonio",
    "tesorero": "MACHADO, Juan Angel"
  },
  {
    "numero": 41,
    "nombre": "Consorcio Caminero Nº41 \"La chiquita\"",
    "localidad": "La chiquita",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.691083,
    "longitude": -60.301494,
    "red_km": 181.28,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 181.28,
    "presidente": "NOVAK, Jose Ernesto",
    "vicepresidente": "VEGA, Jose Antonio",
    "secretario": "AZNAR, Alexis Leonardo",
    "tesorero": "FOGAR, Roberto Daniel"
  },
  {
    "numero": 43,
    "nombre": "Consorcio Caminero Nº43 \"Sáenz Peña\"",
    "localidad": "Sáenz Peña",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.703523,
    "longitude": -60.448528,
    "red_km": 301.59,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 301.59,
    "presidente": "MEDINA Dante Cesar",
    "vicepresidente": "TRNOVSKY, Vicente Vladimiro",
    "secretario": "BROLLO, Mario Javier",
    "tesorero": "AVALOS, Basilio Daniel"
  },
  {
    "numero": 46,
    "nombre": "Consorcio Caminero Nº46 \"Avia terai\"",
    "localidad": "Avia terai",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.682218,
    "longitude": -60.730854,
    "red_km": 192.31,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 192.31,
    "presidente": "BABIJ, Wladimiro",
    "vicepresidente": "LISONSKI, Roberto Antonio",
    "secretario": "PENIDA, Andres",
    "tesorero": "PEREZ, Mateo José"
  },
  {
    "numero": 47,
    "nombre": "Consorcio Caminero Nº47 \"La matanza\"",
    "localidad": "La matanza",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.520865,
    "longitude": -60.185593,
    "red_km": 205.2,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 205.2,
    "presidente": "RADOJKOVIC, Pedro Pablo",
    "vicepresidente": "MATIJASEVICH, Mario",
    "secretario": "BRUICH, Damian Daniel",
    "tesorero": "MATIJASEVICH, Mario Fernando"
  },
  {
    "numero": 51,
    "nombre": "Consorcio Caminero Nº51 \"Bajo Hondo Grande\"",
    "localidad": "Bajo Hondo Grande",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.862863,
    "longitude": -60.549774,
    "red_km": 270.85,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 270.85,
    "presidente": "CHAICOVSKY, Juan Carlos",
    "vicepresidente": "SERRANO, Raul Alberto",
    "secretario": "ROMUCHEWSKY, Pablo",
    "tesorero": "SZKARLATIUK, Daniel Eduardo"
  },
  {
    "numero": 52,
    "nombre": "Consorcio Caminero Nº52 \"Bajo hondo chico\"",
    "localidad": "Bajo hondo chico",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.983955,
    "longitude": -60.429045,
    "red_km": 149.95,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 149.95,
    "presidente": "MIKULAS, Juan Roberto",
    "vicepresidente": "SERRANO, Raul Alberto",
    "secretario": "CERNY, Carlos Antonio",
    "tesorero": "PEGORARO, Jose Ariel"
  },
  {
    "numero": 53,
    "nombre": "Consorcio Caminero Nº53 \"Rio muerto\"",
    "localidad": "Rio muerto",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.310557,
    "longitude": -61.651906,
    "red_km": 549.48,
    "red_primaria": 0,
    "red_secundaria": 47.99,
    "red_terciaria": 501.49,
    "presidente": "GARCIA, Claudio Leandro",
    "vicepresidente": "ANGELI, Ruben Dario",
    "secretario": "SALVI, Mirna Adela",
    "tesorero": "MONTENEGRO, Alberto Juan Danie"
  },
  {
    "numero": 61,
    "nombre": "Consorcio Caminero Nº61 \"Las tres colonias\"",
    "localidad": "Las tres colonias",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.422745,
    "longitude": -59.874234,
    "red_km": 134.31,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 134.31,
    "presidente": "RODRIGUEZ, Alexander Juan",
    "vicepresidente": "TREVISAN, Fernando Javier",
    "secretario": "TREVISAN, Olga Amelia",
    "tesorero": "SPINENHIRN, Augusto Waldemar"
  },
  {
    "numero": 68,
    "nombre": "Consorcio Caminero Nº68 \"La Tigra\"",
    "localidad": "La Tigra",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -27.105842,
    "longitude": -60.580454,
    "red_km": 245.59,
    "red_primaria": 0,
    "red_secundaria": 5.92,
    "red_terciaria": 239.67,
    "presidente": "TRNOVSKY, José Antonio",
    "vicepresidente": "KRASULAK, Jorge Gabriel",
    "secretario": "KRASULAK, Juan Carlos",
    "tesorero": "POLISZUK, Javier Adolfo"
  },
  {
    "numero": 69,
    "nombre": "Consorcio Caminero Nº69 \"Taco Pozo\"",
    "localidad": "Taco Pozo",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -25.6131,
    "longitude": -63.258817,
    "red_km": 421.3,
    "red_primaria": 68.33,
    "red_secundaria": 36.78,
    "red_terciaria": 316.19,
    "presidente": "VILLALBA, Ramon Rene",
    "vicepresidente": "CARO, Martin",
    "secretario": "PERALTA Walter Fabian",
    "tesorero": "FLORES, Daniel Eduardo"
  },
  {
    "numero": 74,
    "nombre": "Consorcio Caminero Nº74 \"Los frentones\"",
    "localidad": "Los frentones",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.410579,
    "longitude": -61.415414,
    "red_km": 372.48,
    "red_primaria": 0,
    "red_secundaria": 46.31,
    "red_terciaria": 326.17,
    "presidente": "GOMEZ, Cristian Alexander",
    "vicepresidente": "MONTORO, Adrian Alejandro",
    "secretario": "LOTO, Ramona Felipa",
    "tesorero": "WOODS, Enrique Carlos"
  },
  {
    "numero": 77,
    "nombre": "Consorcio Caminero Nº77 \"Cnia. Aborigen\"",
    "localidad": "Cnia. Aborigen",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.953645,
    "longitude": -60.201438,
    "red_km": 121.63,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 121.63,
    "presidente": "MIRANDA, Baltazar",
    "vicepresidente": "PAZ, Bernardino",
    "secretario": "CHARA, Demetrio",
    "tesorero": "SANCHEZ, Delio"
  },
  {
    "numero": 84,
    "nombre": "Consorcio Caminero Nº84 \"Picada 60\"",
    "localidad": "Picada 60",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -25.104258,
    "longitude": -62.65848,
    "red_km": 293.24,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 293.24,
    "presidente": "ORQUERA, Desalin",
    "vicepresidente": "ROJAS, Blanca Lilia",
    "secretario": "BERON, Juan",
    "tesorero": "MALDONADO, Sotero Elias"
  },
  {
    "numero": 109,
    "nombre": "Consorcio Caminero Nº109 \"Col. Gral. Paz\"",
    "localidad": "Col. Gral. Paz",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.675104,
    "longitude": -60.199188,
    "red_km": 167.57,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 167.57,
    "presidente": "DE DOMINGO, Orlando Antonio",
    "vicepresidente": "AGUIRRE, Victor",
    "secretario": "DE DOMINGO, Maria Alejandra",
    "tesorero": "PIRIS, Hermindo Vicente"
  },
  {
    "numero": 110,
    "nombre": "Consorcio Caminero Nº110 \"La montenegrina\"",
    "localidad": "La montenegrina",
    "zona": "ZII",
    "color": "#fb6a4a",
    "latitude": -26.99631,
    "longitude": -60.686104,
    "red_km": 267.21,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 267.21,
    "presidente": "DOMBROVSKY, Dante Joel",
    "vicepresidente": "POPOVICH, Mateo Miguel",
    "secretario": "CAPITANICH, Héctor Leonardo",
    "tesorero": "MONZON, Dagoberto José"
  },
  {
    "numero": 1,
    "nombre": "Consorcio Caminero Nº01 \"General Capdevila\"",
    "localidad": "General Capdevila",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.422249,
    "longitude": -61.477299,
    "red_km": 136.13,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 136.13,
    "presidente": "VILLAFAÑE, Ramón Angel",
    "vicepresidente": "HERLE, Nelson Ariel",
    "secretario": "HERLE, Erica Cristina",
    "tesorero": "HERLE, Gerardo Olegario"
  },
  {
    "numero": 2,
    "nombre": "Consorcio Caminero Nº02 \"Gancedo\"",
    "localidad": "Gancedo",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.491568,
    "longitude": -61.669344,
    "red_km": 307.56,
    "red_primaria": 72.78,
    "red_secundaria": 0,
    "red_terciaria": 234.78,
    "presidente": "PARRA, Carlos Alberto",
    "vicepresidente": "OVIEDO, Javier Orlando",
    "secretario": "RIOS, Segundo Oscar",
    "tesorero": "MARCANTELLI, Jose Luis"
  },
  {
    "numero": 4,
    "nombre": "Consorcio Caminero Nº04 \"Santa Sylvina\"",
    "localidad": "Santa Sylvina",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.826698,
    "longitude": -61.134259,
    "red_km": 409.11,
    "red_primaria": 0,
    "red_secundaria": 36.69,
    "red_terciaria": 372.42,
    "presidente": "KOPP, Hector Fabian",
    "vicepresidente": "SEQUEIRA, Alejandro Ramon",
    "secretario": "BERG, Mario Luis",
    "tesorero": "SCHOCH, Omar Alfredo"
  },
  {
    "numero": 8,
    "nombre": "Consorcio Caminero Nº08 \"Pampa Roldan\"",
    "localidad": "Pampa Roldan",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.085414,
    "longitude": -61.285399,
    "red_km": 326.77,
    "red_primaria": 0,
    "red_secundaria": 14.01,
    "red_terciaria": 312.76,
    "presidente": "MARTIN, Norberto",
    "vicepresidente": "SPAHN, Otto Rigoberto",
    "secretario": "KUBLER, Aldino Ariel",
    "tesorero": "WITT, Eliseo Alberto"
  },
  {
    "numero": 10,
    "nombre": "Consorcio Caminero Nº10 \"Meson de Fierro\"",
    "localidad": "Meson de Fierro",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.4317,
    "longitude": -61.015458,
    "red_km": 212.0,
    "red_primaria": 0,
    "red_secundaria": 13.36,
    "red_terciaria": 198.64,
    "presidente": "RUCKSTUHL, Oscar Alfredo",
    "vicepresidente": "CURUTCHET, Claudio Osvaldo",
    "secretario": "VICARIO, Oscar Alfredo",
    "tesorero": "ESTRADA, Jose Luis"
  },
  {
    "numero": 113,
    "nombre": "Consorcio Caminero Nº113 \"Pampa Iporá Guazú\"",
    "localidad": "Pampa Iporá Guazú",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -26.884747,
    "longitude": -61.379641,
    "red_km": 464.95,
    "red_primaria": 0,
    "red_secundaria": 59.33,
    "red_terciaria": 405.62,
    "presidente": "LEDESMA, Raul Rosendo",
    "vicepresidente": "LEGUIZAMON, Rosendo Humberto",
    "secretario": "ALVAREZ, Hugo Antonio",
    "tesorero": "LEGUIZAMON, Ricardo Hugo"
  },
  {
    "numero": 14,
    "nombre": "Consorcio Caminero Nº14 \"Charata\"",
    "localidad": "Charata",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.217705,
    "longitude": -61.18201,
    "red_km": 513.12,
    "red_primaria": 0,
    "red_secundaria": 34.15,
    "red_terciaria": 478.97,
    "presidente": "AQUILINO, Marcelo",
    "vicepresidente": "SARTOR, Jorge Luis",
    "secretario": "VICARIO, Omar Jorge",
    "tesorero": "RICHTER, Guillermo German"
  },
  {
    "numero": 17,
    "nombre": "Consorcio Caminero Nº17 \"Pampa Landriel\"",
    "localidad": "Pampa Landriel",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.39544,
    "longitude": -61.102071,
    "red_km": 168.02,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 168.02,
    "presidente": "CHAPARRO, Mabel Edith",
    "vicepresidente": "PITZUS, Ricardo Eliseo",
    "secretario": "PITZUS, Alexis Daniel",
    "tesorero": "CABUS, Jorge Osvaldo"
  },
  {
    "numero": 20,
    "nombre": "Consorcio Caminero Nº20 \"Chorotis\"",
    "localidad": "Chorotis",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.91654,
    "longitude": -61.401641,
    "red_km": 419.84,
    "red_primaria": 0,
    "red_secundaria": 70.14,
    "red_terciaria": 349.7,
    "presidente": "VUCKO, Ivan",
    "vicepresidente": "IBAÑEZ, Ramon Eduardo",
    "secretario": "HERRERA, Fabian Roberto",
    "tesorero": "CEJAS, Ismael Ruben"
  },
  {
    "numero": 23,
    "nombre": "Consorcio Caminero Nº23 \"Coronel Du Graty\"",
    "localidad": "Coronel Du Graty",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.685942,
    "longitude": -60.903176,
    "red_km": 227.95,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 227.95,
    "presidente": "ALBRECHT, Hugo Aldo",
    "vicepresidente": "WERNER, Néstor Humberto",
    "secretario": "RICZA, Eduardo Bruno",
    "tesorero": "MATERSKY, Miguel Ángel"
  },
  {
    "numero": 27,
    "nombre": "Consorcio Caminero Nº27 \"Haumonia\"",
    "localidad": "Haumonia",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.292611,
    "longitude": -60.409638,
    "red_km": 189.59,
    "red_primaria": 0,
    "red_secundaria": 44.47,
    "red_terciaria": 145.12,
    "presidente": "WALTER, Alberto René",
    "vicepresidente": "PETRUNIOR, Néstor Esteban",
    "secretario": "DUBRAVA, Vanina Noelia",
    "tesorero": "GOMEZ FERRER, Myrna"
  },
  {
    "numero": 31,
    "nombre": "Consorcio Caminero Nº31 \"Las Breñas\"",
    "localidad": "Las Breñas",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.084638,
    "longitude": -61.081815,
    "red_km": 537.67,
    "red_primaria": 0,
    "red_secundaria": 54.07,
    "red_terciaria": 483.6,
    "presidente": "FERNANDEZ, Ruben Alberto",
    "vicepresidente": "SANKO, Nestor German",
    "secretario": "KOTULEVICH, Jaime Andres",
    "tesorero": "SCHUAP, Raul Oscar"
  },
  {
    "numero": 32,
    "nombre": "Consorcio Caminero Nº32 \"Villa Angela\"",
    "localidad": "Villa Angela",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.617539,
    "longitude": -60.784143,
    "red_km": 256.72,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 256.72,
    "presidente": "HRYCYNA, Luis Pedro",
    "vicepresidente": "KLATT, Juan",
    "secretario": "ZAGO, Rubén Luis",
    "tesorero": "GUZOWSKI, Roberto"
  },
  {
    "numero": 33,
    "nombre": "Consorcio Caminero Nº33 \"Colonia Domingo Matheu\"",
    "localidad": "Colonia Domingo Matheu",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.426912,
    "longitude": -60.726045,
    "red_km": 205.23,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 205.23,
    "presidente": "LEVAY, Victor Hugo",
    "vicepresidente": "TOMASINI, Tomaso Miguel",
    "secretario": "SPIGUEL, Jorge Juan Andrés",
    "tesorero": "BISCHOF, Jose Luis"
  },
  {
    "numero": 34,
    "nombre": "Consorcio Caminero Nº34 \"La Clotilde\"",
    "localidad": "La Clotilde",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.177573,
    "longitude": -60.625172,
    "red_km": 233.7,
    "red_primaria": 0,
    "red_secundaria": 16.12,
    "red_terciaria": 217.58,
    "presidente": "GRYB, Juan Carlos",
    "vicepresidente": "SOWA, Carlos Javier",
    "secretario": "KOBLUK, David Antonio",
    "tesorero": "QUERCI, Rubén Alfredo"
  },
  {
    "numero": 39,
    "nombre": "Consorcio Caminero Nº39 \"Enrique Urien\"",
    "localidad": "Enrique Urien",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.738811,
    "longitude": -60.455773,
    "red_km": 402.17,
    "red_primaria": 0,
    "red_secundaria": 82.53,
    "red_terciaria": 319.64,
    "presidente": "BARONI, Miguel Angel",
    "vicepresidente": "MICHELUD, Ottorino",
    "secretario": "LEDESMA, Julia Rosa",
    "tesorero": "KNESEVICH, Adán"
  },
  {
    "numero": 42,
    "nombre": "Consorcio Caminero Nº42 \"Hermoso Campo\"",
    "localidad": "Hermoso Campo",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.611627,
    "longitude": -61.343116,
    "red_km": 495.22,
    "red_primaria": 0,
    "red_secundaria": 41.65,
    "red_terciaria": 453.57,
    "presidente": "GUTIERREZ, Héctor Fernando",
    "vicepresidente": "BRAIDOT, Oscar Gerardo",
    "secretario": "TEHAN, Mario Germán",
    "tesorero": "ACOSTA, Luis Alberto"
  },
  {
    "numero": 48,
    "nombre": "Consorcio Caminero Nº48 \"Villa Berthet\"",
    "localidad": "Villa Berthet",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.292044,
    "longitude": -60.409296,
    "red_km": 343.95,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 343.95,
    "presidente": "FERNANDEZ, Diego Oscar",
    "vicepresidente": "MOREL, Adolfo Gustavo",
    "secretario": "MEZA, Daniel Hernan",
    "tesorero": "ALVAREZ, Victor Arnaldo"
  },
  {
    "numero": 55,
    "nombre": "Consorcio Caminero Nº55 \"Tres Estacas\"",
    "localidad": "Tres Estacas",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -26.922038,
    "longitude": -61.625331,
    "red_km": 307.6,
    "red_primaria": 0,
    "red_secundaria": 47.68,
    "red_terciaria": 259.92,
    "presidente": "CIANCIO, Daniel Osvaldo",
    "vicepresidente": "BRAVO, Sergio Ruben",
    "secretario": "BRAVO, Raul Agustin",
    "tesorero": "DE FILIPPI, Hector Jose"
  },
  {
    "numero": 56,
    "nombre": "Consorcio Caminero Nº56 \"General Pinedo\"",
    "localidad": "General Pinedo",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.331012,
    "longitude": -61.277196,
    "red_km": 421.28,
    "red_primaria": 0,
    "red_secundaria": 11.38,
    "red_terciaria": 409.9,
    "presidente": "BON, Orlando Rubenc",
    "vicepresidente": "BRUA, Ricardo Oscar",
    "secretario": "PERALTA, Paulo",
    "tesorero": "GALEANO, Lucia Amalia"
  },
  {
    "numero": 58,
    "nombre": "Consorcio Caminero Nº58 \"Campo del Banco\"",
    "localidad": "Campo del Banco",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.678158,
    "longitude": -61.053001,
    "red_km": 201.7,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 201.7,
    "presidente": "YENEI, Jorge Alberto",
    "vicepresidente": "BUYATTI, Rene Oscar",
    "secretario": "KODÑIA, Oscar Basilio",
    "tesorero": "KURYLOWICZ, Carlos Ricardo"
  },
  {
    "numero": 60,
    "nombre": "Consorcio Caminero Nº60 \"San Bernardo\"",
    "localidad": "San Bernardo",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.284868,
    "longitude": -60.716653,
    "red_km": 271.22,
    "red_primaria": 0,
    "red_secundaria": 7.92,
    "red_terciaria": 263.3,
    "presidente": "TOURN, Walter Eduardo",
    "vicepresidente": "BALUK, Eugenio Carlos",
    "secretario": "GONZALEZ, Diego Hernan",
    "tesorero": "DICKAU, Nestor Omar"
  },
  {
    "numero": 63,
    "nombre": "Consorcio Caminero Nº63 \"La Avanzada\"",
    "localidad": "La Avanzada",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.784799,
    "longitude": -60.891276,
    "red_km": 166.04,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 166.04,
    "presidente": "RACH, Gerardo Ruben",
    "vicepresidente": "RACH, Roberto Rodolfo",
    "secretario": "AMPUDIA, Carlos Bernardo",
    "tesorero": "BILAN, Mirko Josue"
  },
  {
    "numero": 71,
    "nombre": "Consorcio Caminero Nº71 \"Las Moreras\"",
    "localidad": "Las Moreras",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.509151,
    "longitude": -60.87559,
    "red_km": 194.56,
    "red_primaria": 0,
    "red_secundaria": 16.26,
    "red_terciaria": 178.3,
    "presidente": "COVACH, Victor José",
    "vicepresidente": "SILVA, Luis Alberto",
    "secretario": "PETROVICH, Alan Micael",
    "tesorero": "PETROVICH, Ricardo René"
  },
  {
    "numero": 73,
    "nombre": "Consorcio Caminero Nº73 \"El Triangulo\"",
    "localidad": "El Triangulo",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.165461,
    "longitude": -60.868327,
    "red_km": 261.83,
    "red_primaria": 0,
    "red_secundaria": 34.53,
    "red_terciaria": 227.3,
    "presidente": "ATANASE, Jorge Humberto",
    "vicepresidente": "PANASIUK, Esteban Macario",
    "secretario": "HERASIMCHUK, Eduardo Oscar",
    "tesorero": "BESTANCA, Miguel Angel"
  },
  {
    "numero": 75,
    "nombre": "Consorcio Caminero Nº75 \"El Ñandubay\"",
    "localidad": "El Ñandubay",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.774579,
    "longitude": -60.960817,
    "red_km": 154.1,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 154.1,
    "presidente": "BIELONOVICH, José Luis",
    "vicepresidente": "ZABLOCKY, Juan",
    "secretario": "ALBRECHT, Hugo Rafael",
    "tesorero": "SLIWINSKI, Carlos"
  },
  {
    "numero": 76,
    "nombre": "Consorcio Caminero Nº76 \"Samuhú\"",
    "localidad": "Samuhú",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.520084,
    "longitude": -60.393596,
    "red_km": 109.37,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 109.37,
    "presidente": "PARED, Jose Pedro",
    "vicepresidente": "VOSMICHCA, Ignacio Jose",
    "secretario": "BOIKO, Sergio Alejandro",
    "tesorero": "SOSA, Maximo Abel"
  },
  {
    "numero": 87,
    "nombre": "Consorcio Caminero Nº87 \"Radiscok Belich\"",
    "localidad": "Radiscok Belich",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.092761,
    "longitude": -61.509148,
    "red_km": 232.5,
    "red_primaria": 0,
    "red_secundaria": 14.27,
    "red_terciaria": 218.23,
    "presidente": "BELICH, Marcelo",
    "vicepresidente": "RODRIGUEZ, Pascualino",
    "secretario": "BELICH, Emilio",
    "tesorero": "BELICH, Walter"
  },
  {
    "numero": 91,
    "nombre": "Consorcio Caminero Nº91 \"Los Gansos\"",
    "localidad": "Los Gansos",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.829412,
    "longitude": -60.719911,
    "red_km": 125.15,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 125.15,
    "presidente": "BIRIKEVICH, Angel",
    "vicepresidente": "BUYATTI, Jose Norberto",
    "secretario": "STEFAN, Yanina Soledad",
    "tesorero": "GLIBOTA, Pedro Cesar"
  },
  {
    "numero": 98,
    "nombre": "Consorcio Caminero Nº98 \"El Ñandubay Oeste\"",
    "localidad": "El Ñandubay Oeste",
    "zona": "ZIII",
    "color": "#fdd44c",
    "latitude": -27.706888,
    "longitude": -61.168353,
    "red_km": 155.92,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 155.92,
    "presidente": "D´AOSTA, Gustavo Alfredo",
    "vicepresidente": "BARCO, Teodoro Anselmo",
    "secretario": "FECRABEND, Raul Alberto",
    "tesorero": "GIORDANO, Elio Francisco"
  },
  {
    "numero": 3,
    "nombre": "Consorcio Caminero Nº03 \"Tres Isletas\"",
    "localidad": "Tres Isletas",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -26.332267,
    "longitude": -60.419024,
    "red_km": 490.46,
    "red_primaria": 25.97,
    "red_secundaria": 0,
    "red_terciaria": 464.49,
    "presidente": "TRANGONI, Avelino Eduardo",
    "vicepresidente": "LOZINA, Emilio",
    "secretario": "PROKOPCZUK, Pablo",
    "tesorero": "DEC, Carlos"
  },
  {
    "numero": 100,
    "nombre": "Consorcio Caminero Nº100 \"Fortin Lavalle\"",
    "localidad": "Fortin Lavalle",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -25.709365,
    "longitude": -60.208041,
    "red_km": 293.19,
    "red_primaria": 37.45,
    "red_secundaria": 0,
    "red_terciaria": 255.74,
    "presidente": "BARICHEVAL, Alfredo Francisco",
    "vicepresidente": "PALAVECINO, Rafael",
    "secretario": "ROLDAN, Ireneo",
    "tesorero": "PACHECO, Manuel"
  },
  {
    "numero": 101,
    "nombre": "Consorcio Caminero Nº101 \"Villa Fortuny\"",
    "localidad": "Villa Fortuny",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -25.926052,
    "longitude": -60.598123,
    "red_km": 309.16,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 309.16,
    "presidente": "KLOSTER, Jorge Raúl",
    "vicepresidente": "SCHMITT, Felipe",
    "secretario": "SANDER, Mario Daniel",
    "tesorero": "FERSTER, Eduardo Ricardo"
  },
  {
    "numero": 103,
    "nombre": "Consorcio Caminero Nº103 \"Fuerte Esperanza\"",
    "localidad": "Fuerte Esperanza",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -25.158937,
    "longitude": -61.842753,
    "red_km": 514.22,
    "red_primaria": 39.79,
    "red_secundaria": 47.07,
    "red_terciaria": 427.36,
    "presidente": "CORREA, Horacio",
    "vicepresidente": "GONZALEZ, Ramon Bernabe",
    "secretario": "PEREZ, Victor Hugo",
    "tesorero": "MANSILLA, Claudio"
  },
  {
    "numero": 18,
    "nombre": "Consorcio Caminero Nº18 \"Castelli\"",
    "localidad": "Castelli",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -25.844884,
    "longitude": -60.835857,
    "red_km": 611.27,
    "red_primaria": 26.52,
    "red_secundaria": 0,
    "red_terciaria": 584.75,
    "presidente": "CABANA, Maria Emilia",
    "vicepresidente": "STEBNER, Ricardo",
    "secretario": "RAUSCH, Javier Enrique",
    "tesorero": "LORENZO, Lucas David"
  },
  {
    "numero": 21,
    "nombre": "Consorcio Caminero Nº21 \"Villa Rio Bermejito\"",
    "localidad": "Villa Rio Bermejito",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -25.642987,
    "longitude": -60.264992,
    "red_km": 277.82,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 277.82,
    "presidente": "FIGUEROA, Genaro",
    "vicepresidente": "MORIENEGA, Alberto",
    "secretario": "ROLHEISER, Hector Jose",
    "tesorero": "CABALLERO, Oscar Luis"
  },
  {
    "numero": 49,
    "nombre": "Consorcio Caminero Nº49 \"Bulinky Correa\"",
    "localidad": "Bulinky Correa",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -24.819245,
    "longitude": -62.484109,
    "red_km": 252.08,
    "red_primaria": 25.8,
    "red_secundaria": 0,
    "red_terciaria": 226.28,
    "presidente": "VIZGARRA, Juan Marcelo",
    "vicepresidente": "LUNA, Juan Navor",
    "secretario": "VIZGARRA, Elvira Ramona",
    "tesorero": "SANTILLAN, Nicolas Antonio"
  },
  {
    "numero": 50,
    "nombre": "Consorcio Caminero Nº50 \"Las Hacheras\"",
    "localidad": "Las Hacheras",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -25.387202,
    "longitude": -60.991587,
    "red_km": 380.83,
    "red_primaria": 0,
    "red_secundaria": 45.03,
    "red_terciaria": 335.8,
    "presidente": "ALBORNOZ, Antonio Remberto",
    "vicepresidente": "CUELLAR, Nilda",
    "secretario": "VILLALBA, Nery Ignacio",
    "tesorero": "PEREYRA, Raul Eduardo"
  },
  {
    "numero": 59,
    "nombre": "Consorcio Caminero Nº59 \"Fortin Frias\"",
    "localidad": "Fortin Frias",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -24.566237,
    "longitude": -62.236621,
    "red_km": 520.51,
    "red_primaria": 60.71,
    "red_secundaria": 0,
    "red_terciaria": 459.8,
    "presidente": "NAVARRETE, Oscar",
    "vicepresidente": "NAVARRETE, Pascual",
    "secretario": "PARADA, Vilma",
    "tesorero": "NAVARRETE, Valentin"
  },
  {
    "numero": 72,
    "nombre": "Consorcio Caminero Nº72 \"El Boqueron\"",
    "localidad": "El Boqueron",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -26.212768,
    "longitude": -60.253491,
    "red_km": 161.47,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 161.47,
    "presidente": "ALFONSO, Angel Santos",
    "vicepresidente": "ALCARAZ, Martires Justo",
    "secretario": "IMFELD, Emilio Norberto",
    "tesorero": "INSAURRALDE, Alejandro"
  },
  {
    "numero": 78,
    "nombre": "Consorcio Caminero Nº78 \"Km82 Juana Azurduy\"",
    "localidad": "Km82 Juana Azurduy",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -25.560074,
    "longitude": -61.509898,
    "red_km": 447.19,
    "red_primaria": 50.74,
    "red_secundaria": 0,
    "red_terciaria": 396.45,
    "presidente": "GONZALEZ, Juan Carlos",
    "vicepresidente": "JUAREZ, Martin Jacinto",
    "secretario": "MONTOYA, Carlos Simon",
    "tesorero": "PIWOWARCZUK, Teodoro Pedro"
  },
  {
    "numero": 79,
    "nombre": "Consorcio Caminero Nº79 \"La Rinconada\"",
    "localidad": "La Rinconada",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -26.26585,
    "longitude": -60.453915,
    "red_km": 363.21,
    "red_primaria": 28.25,
    "red_secundaria": 0,
    "red_terciaria": 334.96,
    "presidente": "SVEDA, Andres Miguel",
    "vicepresidente": "JUAREZ, Roberto Carlos",
    "secretario": "MONTOYA, Carlos Simon",
    "tesorero": "PIWOWARCZUK, Teodoro Pedro"
  },
  {
    "numero": 80,
    "nombre": "Consorcio Caminero Nº80 \"La Piramide\"",
    "localidad": "La Piramide",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -25.644087,
    "longitude": -61.911568,
    "red_km": 349.88,
    "red_primaria": 91.65,
    "red_secundaria": 0,
    "red_terciaria": 258.23,
    "presidente": "SOTO, Angela Telesfora",
    "vicepresidente": "SOTO, Angel Daniel",
    "secretario": "PEREZ, José Orlando",
    "tesorero": "ALEMAN, Alberto"
  },
  {
    "numero": 81,
    "nombre": "Consorcio Caminero Nº81 \"El Impenetrable\"",
    "localidad": "El Impenetrable",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -25.283584,
    "longitude": -62.32675,
    "red_km": 459.41,
    "red_primaria": 57.53,
    "red_secundaria": 21.47,
    "red_terciaria": 380.41,
    "presidente": "ARGAÑARAZ, Domingo Ramon",
    "vicepresidente": "TEVEZ, Luis Salvador",
    "secretario": "CORREA, Jose Lorenzo",
    "tesorero": "PEREZ, Carlos"
  },
  {
    "numero": 83,
    "nombre": "Consorcio Caminero Nº83 \"La Cangayé\"",
    "localidad": "La Cangayé",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -25.578924,
    "longitude": -60.589678,
    "red_km": 535.33,
    "red_primaria": 0,
    "red_secundaria": 2.43,
    "red_terciaria": 532.9,
    "presidente": "JUAREZ, Felix",
    "vicepresidente": "FRANK, Carlos Ignacio",
    "secretario": "GONZALEZ, Eduardo",
    "tesorero": "SENGER, Carlos"
  },
  {
    "numero": 85,
    "nombre": "Consorcio Caminero Nº85 \"Miraflores\"",
    "localidad": "Miraflores",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -25.649201,
    "longitude": -60.926702,
    "red_km": 922.68,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 922.68,
    "presidente": "SANCHEZ, Oscar Angel",
    "vicepresidente": "KLOSTER, Walter Luis",
    "secretario": "RECHE, Jose",
    "tesorero": "KONRAD, Alejandro Federico"
  },
  {
    "numero": 86,
    "nombre": "Consorcio Caminero Nº86 \"E Sauzalito\"",
    "localidad": "El Sauzalito",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -24.433182,
    "longitude": -61.680381,
    "red_km": 317.6,
    "red_primaria": 122.27,
    "red_secundaria": 0,
    "red_terciaria": 195.33,
    "presidente": "GIANETTI, Luis Miguel",
    "vicepresidente": "SOSA, Rosendo",
    "secretario": "METZ, Angel Damián",
    "tesorero": "SALAZAR, Dante"
  },
  {
    "numero": 88,
    "nombre": "Consorcio Caminero Nº88 \"Colonia El 44\"",
    "localidad": "Colonia El 44",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -26.011806,
    "longitude": -60.521576,
    "red_km": 265.38,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 265.38,
    "presidente": "STACH, Claudio Omar",
    "vicepresidente": "CABRERA, Rolando Javier",
    "secretario": "KALOUS, Claudio Andres",
    "tesorero": "ROLLHAISER, Omar Enrique"
  },
  {
    "numero": 89,
    "nombre": "Consorcio Caminero Nº89 \"Raices Chaqueñas\"",
    "localidad": "Raices Chaqueñas",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -26.281326,
    "longitude": -60.702409,
    "red_km": 191.5,
    "red_primaria": 27.63,
    "red_secundaria": 0,
    "red_terciaria": 163.87,
    "presidente": "CACERES, Mario",
    "vicepresidente": "ROMERO, Rosa Lina",
    "secretario": "VILLALONGA, Vilma Rosa",
    "tesorero": "MONZON, Higinio"
  },
  {
    "numero": 90,
    "nombre": "Consorcio Caminero Nº90 \"El Asustado\"",
    "localidad": "El Asustado",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -25.978209,
    "longitude": -60.27868,
    "red_km": 148.28,
    "red_primaria": 0,
    "red_secundaria": 22.05,
    "red_terciaria": 126.23,
    "presidente": "MIKEL, Jorge",
    "vicepresidente": "VERON, Eusebio",
    "secretario": "ESCOBAR, Isidro Raul",
    "tesorero": "ESCOBAR, Javier"
  },
  {
    "numero": 95,
    "nombre": "Consorcio Caminero Nº95 \"Pampa Toloza\"",
    "localidad": "Pampa Toloza",
    "zona": "ZIV",
    "color": "#74c476",
    "latitude": -26.054771,
    "longitude": -60.739139,
    "red_km": 474.35,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 474.35,
    "presidente": "SMICALO, David Nazareno",
    "vicepresidente": "KRONEMBERGER, Jose Aurelio",
    "secretario": "KRONEMBERGER, Jose Alberto",
    "tesorero": "RESLER, Juan Miguel"
  },
  {
    "numero": 6,
    "nombre": "Consorcio Caminero N° 06 \"Selvas Rio de Oro\"",
    "localidad": "Selvas Rio de Oro",
    "zona": "ZV",
    "color": "#9e9ac8",
    "latitude": -26.802604,
    "longitude": -58.955501,
    "red_km": 155.48,
    "red_primaria": 0,
    "red_secundaria": 51.32,
    "red_terciaria": 104.16,
    "presidente": "MITOIRE, Estela Carina",
    "vicepresidente": "ALONSO, Alberto Martin",
    "secretario": "REYNOZO, Cristobal Jose",
    "tesorero": "HUGUENIN, Abel"
  },
  {
    "numero": 108,
    "nombre": "Consorcio Caminero N° 108 \"La Aurora\"",
    "localidad": "La Aurora",
    "zona": "ZV",
    "color": "#9e9ac8",
    "latitude": -26.382635,
    "longitude": -59.037845,
    "red_km": 136.52,
    "red_primaria": 0,
    "red_secundaria": 76.34,
    "red_terciaria": 60.18,
    "presidente": "RODRIGUEZ, Cesar Enrique",
    "vicepresidente": "CURA, Andres Ceri",
    "secretario": "ALTAMIRANO, Faustino Amadeo",
    "tesorero": "LEZCANO, Antonio Constancio"
  },
  {
    "numero": 11,
    "nombre": "Consorcio Caminero N° 11 \"Zapallar Norte\"",
    "localidad": "Zapallar Norte",
    "zona": "ZV",
    "color": "#9e9ac8",
    "latitude": -26.46632,
    "longitude": -59.373053,
    "red_km": 143.91,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 143.91,
    "presidente": "CODUTTI, Guillermo Omar",
    "vicepresidente": "CODUTTI, Dario Omar",
    "secretario": "VERZILLI, Claudio Alberto",
    "tesorero": "VITER, Marcos Fabián"
  },
  {
    "numero": 19,
    "nombre": "Consorcio Caminero N° 19 \"Pampa del Indio\"",
    "localidad": "Pampa del Indio",
    "zona": "ZV",
    "color": "#9e9ac8",
    "latitude": -26.042812,
    "longitude": -59.939564,
    "red_km": 468.72,
    "red_primaria": 0,
    "red_secundaria": 12.47,
    "red_terciaria": 456.25,
    "presidente": "VALENZUELA, Nestor Javier",
    "vicepresidente": "VUCKO, Jorge Miguel",
    "secretario": "KANJER, Nelson Edgardo",
    "tesorero": "VITER, Marcos Fabián"
  },
  {
    "numero": 28,
    "nombre": "Consorcio Caminero N° 28 \"Laguna Limpia\"",
    "localidad": "Laguna Limpia",
    "zona": "ZV",
    "color": "#9e9ac8",
    "latitude": -26.493377,
    "longitude": -59.681374,
    "red_km": 115.26,
    "red_primaria": 0,
    "red_secundaria": 0,
    "red_terciaria": 115.26,
    "presidente": "RIQUELME, Juan de la Cruz",
    "vicepresidente": "CARBAJAL, Jorge Eduardo",
    "secretario": "VERA MONZON, Gabino",
    "tesorero": "CORREA, Julio Ponciano"
  },
  {
    "numero": 35,
    "nombre": "Consorcio Caminero N° 35 \"Costa Guaycurú\"",
    "localidad": "Costa Guaycurú",
    "zona": "ZV",
    "color": "#9e9ac8",
    "latitude": -26.593463,
    "longitude": -59.381904,
    "red_km": 114.61,
    "red_primaria": 0,
    "red_secundaria": 19.52,
    "red_terciaria": 95.09,
    "presidente": "GOMEZ, Eladio Adolfo",
    "vicepresidente": "TORRES, Edgardo Manuel",
    "secretario": "MORENO, Mario Alberto",
    "tesorero": "ORCASITA, Sergio Luis"
  },
  {
    "numero": 57,
    "nombre": "Consorcio Caminero N° 57 \"Pcia. Roca\"",
    "localidad": "Pcia. Roca",
    "zona": "ZV",
    "color": "#9e9ac8",
    "latitude": -26.13675,
    "longitude": -59.597512,
    "red_km": 165.2,
    "red_primaria": 0,
    "red_secundaria": 18.06,
    "red_terciaria": 147.14,
    "presidente": "BERTOIA, Rolando Delio",
    "vicepresidente": "MATKOVICH, Aldo Javier",
    "secretario": "CUADRA, Roberto",
    "tesorero": "SILVESTRI, Orlando"
  },
  {
    "numero": 66,
    "nombre": "Consorcio Caminero 66 \"Gral. Vedia\"",
    "localidad": "Consorcio Caminero 66 \"Gral. Vedia",
    "zona": "ZV",
    "color": "#9e9ac8",
    "latitude": -26.929483,
    "longitude": -58.657509,
    "red_km": 132.95,
    "red_primaria": 0,
    "red_secundaria": 12.83,
    "red_terciaria": 120.12,
    "presidente": "TASCON, Orlando Raul",
    "vicepresidente": "ZORRILLA, Leon Ladislao",
    "secretario": "ROLON, Erasmo Carlos",
    "tesorero": "ROBLES, Ricardo Sebastián"
  },
  {
    "numero": 70,
    "nombre": "Consorcio Caminero N° 70 \"La Leonesa\"",
    "localidad": "La Leonesa",
    "zona": "ZV",
    "color": "#9e9ac8",
    "latitude": -27.0364,
    "longitude": -58.709728,
    "red_km": 200.23,
    "red_primaria": 0,
    "red_secundaria": 12.5,
    "red_terciaria": 187.73,
    "presidente": "BALBUENA, Hugo César",
    "vicepresidente": "AMARILLA, Emilio Abel",
    "secretario": "CABALLERO, Oscar Luis",
    "tesorero": "AYALA, Ramón Oscar"
  },
  {
    "numero": 96,
    "nombre": "Consorcio Caminero N° 96 \"Colonia La Esperanza\"",
    "localidad": "Colonia La Esperanza",
    "zona": "ZV",
    "color": "#9e9ac8",
    "latitude": -26.512381,
    "longitude": -59.231666,
    "red_km": 138.81,
    "red_primaria": 0,
    "red_secundaria": 38.0,
    "red_terciaria": 100.81,
    "presidente": "ZALAZAR, Hector",
    "vicepresidente": "PISECH, Lida Grisel",
    "secretario": "ZANEL, Alexis Emanuel",
    "tesorero": "PARDO, Ricardo Andres"
  },
  {
    "numero": 99,
    "nombre": "Consorcio Caminero N° 99 \"Campo Winter\"",
    "localidad": "Campo Winter",
    "zona": "ZV",
    "color": "#9e9ac8",
    "latitude": -26.452035,
    "longitude": -59.284648,
    "red_km": 112.99,
    "red_primaria": 0,
    "red_secundaria": 7.41,
    "red_terciaria": 105.58,
    "presidente": "DENIZ, Benjamín",
    "vicepresidente": "MARTINA, Carlos Dante",
    "secretario": "DENIS, Aureliano",
    "tesorero": "MEZA, Argentino Luis"
  }
];

const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const SUPABASE_URL = 'https://lgkcciflxleyipncnvav.supabase.co';

if (!SERVICE_ROLE_KEY) { console.error('Falta SUPABASE_SERVICE_ROLE_KEY'); process.exit(1); }

// Campos de autoridades que NO deben sobreescribirse en filas existentes
const AUTHORITY_FIELDS = ['presidente', 'vicepresidente', 'secretario', 'tesorero'];

async function post(payload, prefer) {
  const res = await fetch(SUPABASE_URL + '/rest/v1/consorcios', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'apikey': SERVICE_ROLE_KEY,
      'Authorization': 'Bearer ' + SERVICE_ROLE_KEY,
      'Prefer': prefer,
    },
    body: JSON.stringify(payload),
  });
  const text = await res.text();
  if (!res.ok) { console.error('Error HTTP', res.status, text); process.exit(1); }
  return res.status;
}

async function seed() {
  // Paso 1: insertar filas NUEVAS con todos los campos (incluye autoridades iniciales).
  // Las filas existentes se ignoran — sus autoridades no se tocan.
  console.log('Paso 1: insertando nuevos consorcios (ignore-duplicates)...');
  const s1 = await post(CONSORCIOS, 'resolution=ignore-duplicates');
  console.log('  Status:', s1);

  // Paso 2: actualizar km/geo en TODAS las filas sin incluir autoridades.
  // Al omitir los campos de autoridades del payload, Supabase no los toca en el ON CONFLICT DO UPDATE.
  const geoPayload = CONSORCIOS.map(c => {
    const row = { ...c };
    for (const f of AUTHORITY_FIELDS) delete row[f];
    return row;
  });
  console.log('Paso 2: actualizando km/geo (merge-duplicates, sin autoridades)...');
  const s2 = await post(geoPayload, 'resolution=merge-duplicates');
  console.log('  Status:', s2);

  console.log('Listo!');
}

seed().catch(e => { console.error(e); process.exit(1); });
